# 전체 프로젝트 워크플로우
# PROJECT_MANAGEMENT_GUIDE를 따르는 M0-M4, P1-P7 전체 구현

version: "2.0"

variables:
  project_name: "full-project"
  test_command: "pytest tests/ -v"
  lint_command: "ruff check ."

plugins:
  fs: "workflow.plugins.fs.FileExistsValidator"
  shell: "workflow.plugins.shell.CommandValidator"

rulesets:
  all_checked:
    - rule: all_checked
      fail_message: "전이 전 모든 체크리스트 항목을 완료해야 합니다"

  user_approved:
    - rule: user_approved
      fail_message: "USER-APPROVE 항목은 검증 토큰이 필요합니다"

  tests_pass:
    - rule: shell
      args:
        cmd: "pytest tests/ -v"
        expect_code: 0
      fail_message: "모든 테스트가 통과해야 합니다"

# =============================================================================
# 마일스톤 레벨 스테이지 (M0 - M4)
# =============================================================================

stages:
  # ---------------------------------------------------------------------------
  # M0: 기술 부채 검토
  # ---------------------------------------------------------------------------
  M0:
    id: "M0"
    label: "기술 부채 검토"
    checklist:
      - "모든 모듈에서 '기술 부채' 검색"
      - "발견된 부채 검토 및 우선순위 지정"
      - "[USER-APPROVE] 이번 마일스톤의 부채 계획 승인"
    transitions:
      - target: "M1"
        conditions:
          - use_ruleset: all_checked

  # ---------------------------------------------------------------------------
  # M1: 마일스톤 계획
  # ---------------------------------------------------------------------------
  M1:
    id: "M1"
    label: "마일스톤 계획"
    checklist:
      - "마일스톤 PRD 문서 생성 (roadmap/m[N]-[name].md)"
      - "마일스톤 목표 및 성공 기준 정의"
      - "페이즈 (3-4개) 및 고수준 목표 식별"
      - "범위 추정 및 의존성 식별"
    transitions:
      - target: "M2"
        conditions:
          - use_ruleset: all_checked

  # ---------------------------------------------------------------------------
  # M2: 마일스톤 논의
  # ---------------------------------------------------------------------------
  M2:
    id: "M2"
    label: "마일스톤 논의"
    checklist:
      - "마일스톤 아키텍처 및 전략 발표"
      - "최소 2개의 사고 도구 적용 (Pre-mortem, Devil's Advocate 등)"
      - "위험, 대안, 트레이드오프 논의"
      - "[USER-APPROVE] 마일스톤 계획에 대한 사용자 명시적 승인 획득"
    transitions:
      - target: "M3"
        conditions:
          - use_ruleset: all_checked

  # ---------------------------------------------------------------------------
  # M3: 브랜치 생성
  # ---------------------------------------------------------------------------
  M3:
    id: "M3"
    label: "브랜치 생성"
    checklist:
      - "메인 브랜치 최신화 확인 (git pull)"
      - "기능 브랜치 생성 (git checkout -b feature/m[N]-[name])"
      - "브랜치 생성 확인 (git branch --show-current)"
    transitions:
      - target: "P1"
        conditions:
          - use_ruleset: all_checked

  # ---------------------------------------------------------------------------
  # M4: 마일스톤 마무리
  # ---------------------------------------------------------------------------
  M4:
    id: "M4"
    label: "마일스톤 마무리"
    checklist:
      - "전체 E2E 테스트 스위트 실행"
      - "메인 브랜치로 전환 (git checkout main)"
      - "최신 변경사항 풀 (git pull)"
      - "기능 브랜치 병합 (필요시 충돌 해결)"
      - "원격에 푸시 (git push)"
      - "roadmap/current.md 업데이트 - 마일스톤 완료 표시"
      - "시스템 변경 시 ARCHITECTURE.md 업데이트"
    transitions:
      - target: "M0"
        conditions:
          - use_ruleset: all_checked

# =============================================================================
# 페이즈 레벨 스테이지 (P1 - P7)
# =============================================================================

  # ---------------------------------------------------------------------------
  # P1: 페이즈 계획
  # ---------------------------------------------------------------------------
  P1:
    id: "P1"
    label: "페이즈 계획"
    checklist:
      - "이 페이즈의 목표에 대한 마일스톤 PRD 검토"
      - "이 페이즈의 구체적인 산출물 정의"
      - "필요시 PRD에 페이즈 세부사항 업데이트"
    transitions:
      - target: "P2"
        conditions:
          - use_ruleset: all_checked

  # ---------------------------------------------------------------------------
  # P2: 페이즈 논의
  # ---------------------------------------------------------------------------
  P2:
    id: "P2"
    label: "페이즈 논의"
    checklist:
      - "상세 기능 설계 제안 (UX, 데이터 구조, 클래스)"
      - "사용자와 기술적 접근 방식 논의"
      - "잠재적 위험 또는 블로커 식별"
      - "[USER-APPROVE] 스펙 작성 전 사용자 승인 획득"
    transitions:
      - target: "P3"
        conditions:
          - use_ruleset: all_checked

  # ---------------------------------------------------------------------------
  # P3: 스펙
  # ---------------------------------------------------------------------------
  P3:
    id: "P3"
    label: "스펙 작성"
    checklist:
      - "기능 모듈 생성/업데이트 (새 기능인 경우)"
      - "spec.md에 클래스/데이터 구조 및 메서드 시그니처 업데이트"
      - "current.md에 관련 파일 섹션 업데이트"
      - "ARCHITECTURE.md 업데이트 필요 여부 확인 (결정 문서화)"
      - "spec-validator 에이전트 호출 (가능한 경우)"
      - "spec-validator 발견사항 처리"
    transitions:
      - target: "P4"
        conditions:
          - use_ruleset: all_checked

  # ---------------------------------------------------------------------------
  # P4: 구현
  # ---------------------------------------------------------------------------
  P4:
    id: "P4"
    label: "구현"
    checklist:
      - "스펙 구조 기반 파일/폴더 생성"
      - "스펙을 정확히 따라 로직 구현"
      - "임포트가 모듈 의존성과 일치하는지 확인"
      - "구조 검증 실행 (mcontext --structure)"
    transitions:
      - target: "P5"
        conditions:
          - use_ruleset: all_checked

  # ---------------------------------------------------------------------------
  # P5: 테스트
  # ---------------------------------------------------------------------------
  P5:
    id: "P5"
    label: "테스트"
    checklist:
      - "새 기능에 대한 단위 테스트 작성"
      - "통합/시나리오 테스트 작성"
      - "모든 테스트 실행 및 통과 확인"
      - "테스트 커버리지 요구사항 충족 확인"
    transitions:
      - target: "P6"
        conditions:
          - use_ruleset: all_checked

  # ---------------------------------------------------------------------------
  # P6: 셀프 리뷰
  # ---------------------------------------------------------------------------
  P6:
    id: "P6"
    label: "셀프 리뷰"
    checklist:
      - "스펙 정합성: 코드가 스펙 시그니처와 일치하는가?"
      - "에러 처리: 엣지 케이스 (None, empty) 처리되었는가?"
      - "타입 안전성: 타입 힌트가 올바르게 사용되었는가?"
      - "SRP: 각 클래스/함수가 정확히 하나의 일만 하는가?"
      - "코드 품질: 변수명이 설명적인가?"
      - "code-reviewer 에이전트 호출 (가능한 경우)"
      - "code-reviewer 발견사항 처리"
      - "[USER-APPROVE] 마무리 진행을 위한 사용자 승인 획득"
    transitions:
      - target: "P7"
        conditions:
          - use_ruleset: all_checked

  # ---------------------------------------------------------------------------
  # P7: 페이즈 마무리
  # ---------------------------------------------------------------------------
  P7:
    id: "P7"
    label: "페이즈 마무리"
    checklist:
      - "구현이 스펙과 다르면 spec.md 업데이트"
      - "current.md에 새 기술 부채 기록 (또는 해결된 것 표시)"
      - "P3에서 결정이 'Y'였다면 ARCHITECTURE.md 업데이트"
      - "memory_tool check 실행 (가능한 경우)"
      - "컨텍스트 생성 실행 (mcontext --structure)"
      - "PRD에 페이즈 상태 업데이트 (완료 표시)"
      - "설명적인 메시지로 Git 커밋"
      - "타임라인에 완료 기록"
    transitions:
      # 다음 페이즈
      - target: "P1"
        conditions:
          - use_ruleset: all_checked
      # 또는 마일스톤 마무리 (수동 선택)
      - target: "M4"
        conditions:
          - use_ruleset: all_checked
